"""Markdown + PDF report generation."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any

from fpdf import FPDF


def build_markdown_report(
    *,
    title: str,
    workspace_name: str | None = None,
    semantic_summary: str | None = None,
    eda: dict[str, Any] | None = None,
    experiment: dict[str, Any] | None = None,
    explanations: dict[str, Any] | None = None,
    recommendations: list[str] | None = None,
) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# {title}",
        "",
        f"_Generated by Syntrix AI - {now}_",
        "",
    ]
    if workspace_name:
        lines += [f"**Workspace:** {workspace_name}", ""]
    if semantic_summary:
        lines += ["## Dataset overview", "", semantic_summary, ""]
    if eda:
        insights = eda.get("insights") or []
        if insights:
            lines += ["## EDA insights", ""]
            for ins in insights:
                lines.append(f"- **{ins.get('title')}** - {ins.get('detail')}")
            lines.append("")
        summary = eda.get("summary") or {}
        if summary:
            lines += [
                "## Profile summary",
                "",
                f"- Rows: {summary.get('row_count')}",
                f"- Columns: {summary.get('column_count')}",
                f"- Missing cell %: {summary.get('missing_cell_pct')}",
                f"- Duplicate rows: {summary.get('duplicate_row_count')}",
                "",
            ]
    if experiment:
        lines += ["## Experiment results", ""]
        lines.append(f"- Task: `{experiment.get('task_type')}`")
        lines.append(f"- Target: `{experiment.get('target_column')}`")
        lines.append(f"- Best algorithm: `{experiment.get('best_algorithm')}`")
        lines.append(f"- Best score: `{experiment.get('best_score')}`")
        models = experiment.get("models") or []
        if models:
            lines += ["", "Models:", ""]
            for m in models:
                metrics = m.get("metrics") or {}
                lines.append(f"- {m.get('algorithm')}: primary={metrics.get('primary')}")
            lines.append("")
    if explanations:
        lines += ["## Model explanations", ""]
        lines.append(f"Method: `{explanations.get('method')}`")
        global_imp = explanations.get("global") or []
        if global_imp:
            lines += ["", "Top features:", ""]
            for item in global_imp[:15]:
                lines.append(f"- `{item.get('feature')}`: {item.get('importance')}")
            lines.append("")
    recs = recommendations or _default_recommendations(eda, experiment)
    if recs:
        lines += ["## Recommendations", ""]
        for r in recs:
            lines.append(f"- {r}")
        lines.append("")
    lines += ["---", "", "_Syntrix AI portfolio demo report (Markdown + PDF)._"]
    return "\n".join(lines)


def markdown_to_pdf(markdown: str, title: str = "Syntrix Report") -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(left=15, top=15, right=15)
    pdf.set_font("Helvetica", "B", 16)
    _write(pdf, _safe(title), 10)
    pdf.ln(4)
    pdf.set_font("Helvetica", size=11)

    for raw in markdown.splitlines():
        line = raw.rstrip()
        if not line or line.startswith("|---") or set(line) <= {"-", "|", " "}:
            pdf.ln(2)
            continue
        if line.startswith("# "):
            pdf.set_font("Helvetica", "B", 16)
            _write(pdf, _strip_md(_safe(line[2:])), 8)
            pdf.set_font("Helvetica", size=11)
        elif line.startswith("## "):
            pdf.set_font("Helvetica", "B", 13)
            _write(pdf, _strip_md(_safe(line[3:])), 7)
            pdf.set_font("Helvetica", size=11)
        elif line.startswith("- "):
            _write(pdf, "- " + _strip_md(_safe(line[2:])), 6)
        elif line.startswith("|"):
            pdf.set_font("Courier", size=9)
            _write(pdf, _safe(line.replace("|", " ")), 5)
            pdf.set_font("Helvetica", size=11)
        else:
            _write(pdf, _strip_md(_safe(line)), 6)

    out = pdf.output()
    if isinstance(out, (bytes, bytearray)):
        return bytes(out)
    return str(out).encode("latin-1", errors="ignore")


def _write(pdf: FPDF, text: str, h: float) -> None:
    pdf.set_x(pdf.l_margin)
    try:
        pdf.multi_cell(0, h, text or " ")
    except Exception:  # noqa: BLE001
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, h, (text or " ")[:200])


def _strip_md(text: str) -> str:
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"_(.+?)_", r"\1", text)
    text = text.replace("`", "'")
    return text


def _safe(text: str) -> str:
    return (
        text.replace("—", "-")
        .replace("–", "-")
        .replace("·", "-")
        .replace("•", "-")
        .replace("`", "'")
        .encode("latin-1", errors="replace")
        .decode("latin-1")
    )


def _default_recommendations(
    eda: dict[str, Any] | None, experiment: dict[str, Any] | None
) -> list[str]:
    recs: list[str] = []
    if eda and (eda.get("summary") or {}).get("missing_cell_pct", 0) > 5:
        recs.append("Address missing values before production training.")
    if experiment and experiment.get("best_algorithm"):
        recs.append(
            f"Promote '{experiment['best_algorithm']}' as champion and monitor drift on new uploads."
        )
    if not recs:
        recs.append(
            "Validate target definition with stakeholders and re-run AutoML on larger samples."
        )
    return recs
